### ISSUE TITLE
Patching read-only kernel pages

### ISSUE THREAD

**Issue by D0m0** [Siguza/ios-kern-utils#13]
This is most likely not an issue with ios-kern-tools, but I can't find any info on this. Please give some advise!

The latest tools work perfectly on my arm64 iPad Air 9.0.2, including nvpatch.
But when I try using kpatch to modify some bits, the device crashes. The memory is available and can be read with kmem, although it happens to fall into the "big null kernel region". I noticed that nvpatch modifies memory in that region without crashing, so it's not a region problem. My guess is that either mem pages are flagged read-only (but if that's true, why not use vm_protect before calling vm_write in kpatch?), or it's the KPP (is it not disabled by Pangu?), or it's an issue with the A7 TrustZone / Security Extensions / whatever (in that case I guess we just give up?).

Thanks!

**Comment by D0m0** [comment]
Also, if it's a problem with page protection, can I mmap() it for r/w?

**Comment by Siguza** [comment]
You asked a couple of different questions:

- I know that Pangu (and most other jailbreaks) change the permissions of _some_ segments, but not others. AFAIK `__TEXT` is usually patched, but e.g. `_PRELINK_TEXT` isn't.
- Despite access permissions, changes to the `__TEXT` segment will still trigger KPP.
- `nvpatch` only edits memory in the `__DATA.__data` section, interfering with neither of the above.

As for your issue:

- If KPP is the reason (are you patching `__TEXT`?), you'd have to go to great lengths to win that battle - you could ultimately implement Luca's bypass, but... yeah, great lengths. Most of the time there are ways to work around it though, depending on the specific case.
- If page permissions are the issue, then it is possible to edit those, but not via the `vm_*` APIs. For normal memory, XNU keeps so-called "VM objects" around to manage actual page tables mapping, and virtually all memory management code depends on those. For the base region however, only a big NULL mapping exists, which does not reflect the actual page table entries of the region. Basically you'd have to do a manual page table walk.

**Comment by D0m0** [comment]
Thanks, this clears up a lot for me! But does KPP depend on page table permissions, or is there some other hw mechanism involved? And by "ways to work around it" do you mean patching data instead of text?

**Comment by D0m0** [comment]
P.S. Just found this https://github.com/kpwn/iOSRE/wiki/Kernel-Patch-Protection-(KPP)
So this basically answers my first question.

**Comment by Siguza** [comment]
> And by "ways to work around it" do you mean patching data instead of text?

Yes, but also userland adaption. In my experience, patches to code are in the end only about the data that code handles. I think a nice example is the kernel task port, which Pangu just moved to `realhost.special[4]`, thus dropping the need of patching the actual `task_for_pid` code at all - but with the effect that userland now needs to call `host_get_special_port`. I mean, userland stuff could ultimately be handled via a tweak/injected dylib if need be. A more extreme example would be that, if you wanted to have RWX regions in userland, rather than patching the `mprotect` syscall or so, you'd just implement a function in userland that patches page tables directly via tfp0. In the end, it's almost always about the data. ;)

**Comment by D0m0** [comment]
Thanks!!! I guess it's time to close the issue!
