### ISSUE TITLE
[IOS 11.1.1] nvrampatch on iPhone9,3

### ISSUE THREAD

**Issue by zGrEaNz** [Siguza/ios-kern-utils#15]
kdump kinfo kmap kmem kpatch can run without any error, but nvram still have problem.

here is a log file.

https://pastebin.com/Zmgsrm7X

i'm using Electra b6.

**Comment by Siguza** [comment]
Yes, the method `nvpatch` uses to unrestrict variables has been mitigated in iOS 11. There are multiple other ways of doing it, but they're all pretty intrusive and might not play nice with patches applied by the jailbreak itself.  
AFAIK though later releases of Electra add such a patch, and Morpheus at least plans to add one to liberiOS, if he hasn't already.

If and when there emerges an iOS 11 jailbreak, I'll see what I can do about this.

**Comment by stek29** [comment]
`gOFVariables` was moved to `const` section on iOS 11.

Easiest way for now is to temporarily fake IODTNVRAM's vtable, and for that you can use [this](https://github.com/stek29/noncereboot11).

I believe that method can be improved by remapping that function to some other virtual address instead of changing it to `ret 0`, and doing it in a way that places references to `gOFVariables` somewhere where you can allocate writeable memory, but it's not worth it for just setting the nonce or something like that imo.

**Comment by Siguza** [comment]
@stek29 So Electra doesn't install any patch by itself?

**Comment by stek29** [comment]
@Siguza no, it doesn't
