### ISSUE TITLE
Killed:9

### ISSUE THREAD

**Issue by CrypticGit** [Siguza/ios-kern-utils#8]
Installed latest commit and get killed: 9 error when running khead and kdump.
This is for the ios 10 branch.
iPhone 6s N71AP 10.2

**Comment by Siguza** [comment]
Sounds like a code signing issue. The build process should sign them, but just to be sure, could you verify they're signed? And did you install them via deb, or by hand? In the latter case, if you copied them over pre-existing binaries, the signature of the old binary will reain in the cache, and obviously not match the new binary, so it gets killed. If you update binaries by hand, always delete + recreate rather than overwrite.

**Comment by CrypticGit** [comment]
@siguza I tried deb and ldid just incase l'll try to install directly. Also I have a killed: 9 on a lot of exceutables for example python pip, ruby, metasploit, and more. Does this also mean code signing?

**Comment by Siguza** [comment]
Okay, that sounds more like a broken AMFI. Does your syslog say anything?

**Comment by CrypticGit** [comment]
@siguza syslog location in kind of a noob

**Comment by Siguza** [comment]
No location, unfortunately. See [the iPhone wiki](https://www.theiphonewiki.com/wiki/System_Log) for instructions.

**Comment by CrypticGit** [comment]
@Siguza I can't seem to compile ondevide console what shall I do? Do you have a copy or can I use Ryan's deviceconsole?

**Comment by Siguza** [comment]
[ondeviceconsole.zip](https://github.com/Siguza/ios-kern-utils/files/819001/ondeviceconsole.zip)

**Comment by CrypticGit** [comment]
@siguza when I run the commands I still get same killed: 9 but don't see anything other than the same things that continuously show up in ondeviceconsole

**Comment by Siguza** [comment]
Well, it's definitely an issue with your system, and not with kern-utils. This happens before any of my code even runs, so I'm closing this.
